name: Train Model & Save Artifacts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-cml:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Workflow-CI

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install Library
      - name: Install Dependencies
        run: |
          pip install mlflow pandas numpy scikit-learn scipy psutil pyarrow cloudpickle setuptools wheel

      # 4. Jalankan MLflow
      - name: Run MLflow
        env:
          MLFLOW_TRACKING_URI: "file:./mlruns"
        run: |
          mlflow run . --env-manager=local

      # 5. Simpan Hasil (Commit & Push)
      - name: Commit and Push MLflow Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ -d "mlruns" ]; then
            git add mlruns/
            echo "Folder mlruns ditemukan dan ditambahkan ke staging."
          else
            echo "Warning: Folder mlruns tidak ditemukan. Cek script Python Anda."
          
          # Cek status dan commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-save: Model Artifacts from CI [skip ci]" && git pull --rebase origin main && git push)
